// <auto-generated />
namespace MvcBackbone.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class test333d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test333d));
        
        string IMigrationMetadata.Id
        {
            get { return "201304191934126_test333d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
